variables:
  BUILD_OUTPUT_DIR: app/build/outputs/apk

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd cliqzSearch
    npm ci
    mkdir -p build
    npm run build
  displayName: 'Build search (debug)'

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    tasks: 'assembleDebug'
  displayName: 'Assemble Debug'

- script: |
    cd cliqzSearch
    npm run build:prod
  displayName: 'Build search (release)'

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    tasks: 'assembleRelease'
  displayName: 'Assemble Release'

- task: AndroidSigning@2
  inputs:
    apkFiles: '**/release/*.apk'
    jarsign: true
    jarsignerKeystoreFile: 'sam-browser-keys.jks'
    jarsignerKeystorePassword: '$(jarsignerKeystorePassword)'
    jarsignerKeystoreAlias: 'release'
    jarsignerKeyPassword: '$(jarsignerKeyPassword)'
    zipalign: true
    zipalignFile: /usr/local/lib/android/sdk/build-tools/28.0.3/zipalign

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(BUILD_OUTPUT_DIR)/'
    artifactName: apks
  displayName: 'Publish APKs'
